spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VitaliyVoronov/game-engine-configuration
          clone-on-start: true
  application:
    name: game-config-server
server:
  port: 8020